/* This is used to add "Welcome to xFusionCorp Industries!" on top of "This is a Nautilus sample file, created using Ansible!\n"
  So te final output of cat index.html will be
 "Welcome to xFusionCorp Industries!"
 "This is a Nautilus sample file, created using Ansible!"
*/

---
- hosts: all
  become: yes 
  tasks:
    - name: Install httpd web server
      yum:
        name: httpd
        state: present

    - name: Ensure httpd service is running
      service:
        name: httpd
        state: started
        enabled: yes

    - name: Create index.html file
      copy:
        content: "This is a Nautilus sample file, created using Ansible!\n"
        dest: /var/www/html/index.html
        owner: apache
        group: apache
        mode: '0644'

    - name: Add more content to index.html
      lineinfile:
        path: /var/www/html/index.html
        line: "Welcome to xFusionCorp Industries!"
        insertbefore: BOF    
