---
- hosts: all
  become: yes
  tasks:
    - name: Copy the secret file
      copy:
        src: secret_file.txt
        dest: /root/.secret_file.txt  
        
# ansible-playbook -i inventory copy_secrets.yml --ask-vault-pass get_vault_pass.py :- to execute
