---
- hosts: web1
  become: yes
  gather_facts: no
  tasks:
    - name: install firewalld
      yum:
        name: firewalld
        state: present
    - name: start and enable firewalld
      service:
        name: firewalld
        state: started
        enabled: yes
