---
- hosts: web1
  become: yes
  gather_facts: yes
  tasks:
    - name: add firewall rule in internal zone to enable https
      firewalld:
        source: 172.20.1.2
        service: https
        state: enabled
        zone: internal
        permanent: yes
        immediate: yes 
