---
- name: Create index.html on web1
  hosts: web1
  become: yes 
  tasks:
  - lineinfile:
      path: /var/www/html/index.html
      line: 'This line was added using Ansible lineinfile module!'
      create: yes
