---
- hosts: web2
  become: yes
  tasks:
    - name: install httpd and firewalld
      yum:
        name: httpd, firewalld
        state: present

    - name: start/enable httpd and firewalld
      service: 
        name: "{{ item }}"
        state: started
        enabled: yes
      with_items:
        - httpd
        - firwalld

    - name: Change apache port
      replace:
        path: /etc/httpd/conf/httpd.conf
        regexp: "Liten 80"
        replace: "Listen 8082"

    - name: restart apache
      service:
        name: httpd
        state: restarted

    - name: Add firewall for Apache
      firewalld:
        port: 8082/tcp
        zone: public
        permanent: yes
        state: enabled
        immediate: yes
