---
- hosts: all
  become: yes
  tasks:
    - name: Copy blog.txt on App-Server-1
      copy:
        src: /usr/src/dba/blog.txt    
        dest: /opt/dba
        owner: 'tony'
        group: 'tony'
        mode: '0655'
      when: "'stapp01' in inventory_hostname"   

    - name: Copy story.txt on App-Server-2
      copy:
        src: /usr/src/dba/story.txt
        dest: /opt/dba
        owner: 'steve'
        group: 'steve'
        mode: '0655'
      when: "'stapp02' in inventory_hostname"

    - name: Copy media.txt on App-Server-3
      copy:
        src: /usr/src/dba/media.txt
        dest: /opt/dba
        owner: 'banner'
        group: 'banner'
        mode: '0655'
      when: "'stapp03' in inventory_hostname"

# OR you can use the below the playbook

---
- hosts: all
  become: yes
  tasks:
    - name: Copy files to App Servers
      copy:
        src: "/usr/src/dba/{{ item.file }}"
        dest: /opt/dba
        owner: "{{ item.owner }}"
        group: "{{ item.group }}"
        mode: '0655'
      when: "inventory_hostname in item.hostnames"
      loop:
        - { file: 'blog.txt', owner: 'tony', group: 'tony', hostnames: ['stapp01'] }
        - { file: 'story.txt', owner: 'steve', group: 'steve', hostnames: ['stapp02'] }
        - { file: 'media.txt', owner: 'banner', group: 'banner', hostnames: ['stapp03'] }
